"""empty message

Revision ID: d9780888e9a0
Revises: 
Create Date: 2018-01-17 18:44:08.122918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9780888e9a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.String(length=64), nullable=True),
    sa.Column('topics_id', sa.String(length=32), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=32), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=32), nullable=True),
    sa.Column('imgurl', sa.String(length=64), nullable=True),
    sa.Column('house_money', sa.String(length=32), nullable=True),
    sa.Column('usable_area', sa.String(length=32), nullable=True),
    sa.Column('house_type', sa.String(length=32), nullable=True),
    sa.Column('house_style', sa.String(length=32), nullable=True),
    sa.Column('content', sa.String(length=64), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imgurl', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('introduce', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('counts', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('pimg', sa.String(length=32), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_rid'), 'posts', ['rid'], unique=False)
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imgUrl', sa.String(length=32), nullable=True),
    sa.Column('describe', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_img', sa.String(length=64), nullable=True),
    sa.Column('top_title', sa.String(length=32), nullable=True),
    sa.Column('top_content', sa.Text(), nullable=True),
    sa.Column('house_type', sa.String(length=32), nullable=True),
    sa.Column('usable_area', sa.Integer(), nullable=True),
    sa.Column('ratchadapisek', sa.String(length=32), nullable=True),
    sa.Column('decorate_cost', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics_one',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('content', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics_udcontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=32), nullable=True),
    sa.Column('imgurl1', sa.String(length=32), nullable=True),
    sa.Column('imgurl2', sa.String(length=32), nullable=True),
    sa.Column('imgurl3', sa.String(length=32), nullable=True),
    sa.Column('topics_one_id', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('udcontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=32), nullable=True),
    sa.Column('ud_id', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('underdiscussion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('content', sa.String(length=32), nullable=True),
    sa.Column('imgurl', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('phone_num', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('underdiscussion')
    op.drop_table('udcontent')
    op.drop_table('topics_udcontent')
    op.drop_table('topics_one')
    op.drop_table('topics')
    op.drop_table('styles')
    op.drop_index(op.f('ix_posts_rid'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('personal')
    op.drop_table('information')
    op.drop_table('diary')
    op.drop_table('design')
    op.drop_table('collects')
    # ### end Alembic commands ###
